export const tags = [
  { id: 1, name: "竹编工艺" },
  { id: 2, name: "竹雕艺术" },
  { id: 3, name: "竹纸制作" },
  { id: 4, name: "竹乐器" },
  { id: 5, name: "竹建筑" },
  { id: 6, name: "竹诗词" },
  { id: 7, name: "竹画技法" },
  { id: 8, name: "竹食文化" },
  { id: 9, name: "竹医药" },
  { id: 10, name: "竹信仰" },
  { id: 11, name: "竹与茶" },
  { id: 12, name: "竹与酒" },
  { id: 13, name: "竹与清廉" },
  { id: 14, name: "竹与文人" },
  { id: 15, name: "竹与园林" },
  { id: 16, name: "竹与武术" },
  { id: 17, name: "竹与民俗" },
  { id: 18, name: "竹与服饰" },
  { id: 19, name: "竹与生态" },
  { id: 20, name: "竹与科技" },
];